### PR TITLE
Remove deprecated extension of `AbstractTask`

### PR DESCRIPTION
**Pull request by kiwi-oss**
Upon running a Gradle build using this plugin with `--warning-mode=all`, the following message is shown:

> Registering a task with a type that directly extends AbstractTask has been deprecated. This will fail with an error in Gradle 7.0. Consult the upgrading guide for further information: https://docs.gradle.org/6.8.3/userguide/upgrading_version_6.html#abstract_task_deprecated

I made the changes recommended on the linked page, so the plugin should be prepared for 7.0.

### CODE REVIEW

**Review by jekkel — APPROVED** [review]

**Comment by jekkel** [comment]
Thanks! I think this is good to merge. The missing workflow `Analaze (Java)` was disabled accidentally, could you please push another small change (rewording should suffice)?

**Comment by kiwi-oss** [comment]
Thanks, I was wondering about that. I just amended the last commit message, let's see if it runs now.

**Comment by kiwi-oss** [comment]
The checks were successful, however it seems I'm not allowed to merge.

> Merging is blocked
> The base branch restricts merging to authorized users.

**Comment by jekkel** [comment]
> The checks were successful, however it seems I'm not allowed to merge.
> 
> > Merging is blocked
> > The base branch restricts merging to authorized users.

made you a maintainer of the project.

**Pull request merged**
