### PR TITLE
Deploy fix

### PR DESCRIPTION
**Pull request by wind57**
This is still a Draft - but this version works against our helm repo. Tested. 

yeah... exactly what I was afraid of. I did not check the workflows, but I guess you compile with java-8 and this PR has features that where added above that. Pity. Our projects are at least jdk-11.

I will clone this repo internally to our github and support it there. If I find any more issues, I will contribute here also...

### CODE REVIEW

**Comment by jekkel** [comment]
> yeah... exactly what I was afraid of. I did not check the workflows, but I guess you compile with java-8 and this PR has features that where added above that. Pity. Our projects are at least jdk-11.
> 
> I will clone this repo internally to our github and support it there. If I find any more issues, I will contribute here also...

Since java8 is still officially supported by gradle 6 I think it's required to also support it in this plugin. To cleanup the http client code we should maybe use another http client library instead of using the jdk9 client, probably one that's already natively supporting multipart uploads.

**Comment by wind57** [comment]
I've seen that it should be possible to use `URLConnection` for this... would you accept a PR with whatever you already have in place with a `useMultipart` flag for example?

**Comment by wind57** [comment]
@jekkel I am closing this - since the upload works the way it is. It required minor changes on the way we set-up our repo, but not a big deal. thank you for fixing this.

**Comment by jekkel** [comment]
> I've seen that it should be possible to use `URLConnection` for this... would you accept a PR with whatever you already have in place with a `useMultipart` flag for example?

Yes, of course! Would be really nice to keep a natural language alike deploy dsl though.

But it seems you solved the issue from another side. Thanks for your contribution though!

**Pull request closed without merging**
